name: Matrix Configuration

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, ubuntu-22.04.5, windows-latest]
          images: [hello-world, nginx, alpine]
          exclude:
            - os: windows-latest
              images: nginx
            - os: windows-latest
              images: alpine
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run Images on ${{ matrix.images }}
        run: docker run ${{ matrix.images }}